export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION';

export const INITIALIZE_EDITOR = 'INITIALIZE_EDITOR';
export const INITIALIZE_EDITOR_SUCCESS = 'INITIALIZE_EDITOR_SUCCESS';
export const INITIALIZE_EDITOR_FAIL = 'INITIALIZE_EDITOR_FAIL';
export const CLOSE_EDITOR = 'CLOSE_EDITOR';
export const CLEAR_BANNER_ERROR = 'CLEAR_BANNER_ERROR';
export const GET_WEBSITE_CONTENT = 'GET_WEBSITE_CONTENT';
export const GET_WEBSITE_CONTENT_FAIL = 'GET_WEBSITE_CONTENT_FAIL';
export const GET_WEBSITE_CONTENT_SUCCESS = 'GET_WEBSITE_CONTENT_SUCCESS';
